[package]
name = "testdir"
version = "0.1.0"
authors = ["Floris Bruynooghe <flub@devork.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
whoami = "1.0.0"

[dev-dependencies]
tempfile = "3.1.0"
