[package]
name = "testdir"
version = "0.3.0"
authors = ["Floris Bruynooghe <flub@devork.be>"]
edition = "2018"
description = "Semi-persistent, scoped test directories"
repository = "https://hg.sr.ht/~flub/testdir"
documentation = "https://docs.rs/testdir"
license = "MIT OR Apache-2.0"
keywords = ["test", "temp", "temporary", "directory"]
categories = ["development-tools::testing", "filesystem"]

[dependencies]
backtrace = "0.3.55"
#heim-process = "0.1.1-beta.3"
heim = { version = "0.1.0-beta.3", default-features = false, features = ["process"] }
once_cell = "1.5.2"
smol = "1.2"
whoami = "1.0.0"

[dev-dependencies]
tempfile = "3.1.0"
