name: CI

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
   RUST_BACKTRACE: "1"
   RUSTFLAGS: "-Dwarnings"
   RUSTDOCFLAGS: "-Dwarnings"
   RUSTC_WRAPPER: "sccache"
   SCCACHE_GHA_ENABLED: "true"

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: cargo fmt --check
      - run: cargo clippy --no-deps
      - run: cargo doc --no-deps --document-private-items

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: taiki-e/install-action@nextest
      - run: cargo test
      - run: cargo nextest run


